### ISSUE TITLE
ytsr is not a function

### ISSUE THREAD

**Issue by ItsRevolt** [TimeForANinja/node-ytsr#10]
When trying to follow the example in the readme, I get an error saying "ytsr is not a function".

Running node version 10.4.1

**Comment by TimeForANinja** [comment]
What's ur ytsr version?

**Comment by ItsRevolt** [comment]
Version is 0.1.7

**Comment by TimeForANinja** [comment]
looks like i added that feature after pushing to npm...
should be fixed when u do a npm update

ty for letting me know 👍

**Comment by ItsRevolt** [comment]
Yup, looks like it's fixed now. Thanks!
