### ISSUE TITLE
Great library!

### ISSUE THREAD

**Issue by haroldo-ok** [TimeForANinja/node-ytsr#100]
I used your library in my own experimental Youtube search engine: https://github.com/haroldo-ok/youtube-quality-search
It is heavily inspired by Chris Lovejoy's "Valuable YouTube Video Finder" (https://github.com/chris-lovejoy/YouTube-video-finder).

Many thanks! It saved me some time on the prototyping.

**Comment by TimeForANinja** [comment]
your welcome 👌
