### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jurgenjacobsen** [TimeForANinja/node-ytsr#101]
I'd like to congrat you, it's a awesome package but I have a question: How could I make it respond my videoSearch more quickly ? I need it more quick as possible. My actual code is like this: `ytsr('oi lagum', {limit: 1, hl: 'pt', gl: 'BR'})`

Many thanks!

**Comment by TimeForANinja** [comment]
there's no way i know of to make it much faster
you could shave a few nano-seconds parsing less types but the major time-loss is the network request and `limit: 1` or even `page: 1` only do a single one

**Comment by jurgenjacobsen** [comment]
Ok, thanks man!
