### ISSUE TITLE
Error type promotedVideoRenderer is not known

### ISSUE THREAD

**Issue by AntoineMaille** [TimeForANinja/node-ytsr#108]
Hello from times to times i have this error comming up : 
failed at func parseItem: type promotedVideoRenderer is not known
pls post the the files in G:\Projets\Quizzie\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v14.15.3, ytpl: 3.3.0

**Comment by TimeForANinja** [comment]
fixed with https://github.com/TimeForANinja/node-ytsr/commit/29f147b4ca37d2532386c0339c11b8a02a27d671
👍
