### ISSUE TITLE
Cannot read property 'simpleText' of undefined

### ISSUE THREAD

**Issue by ExpMero** [TimeForANinja/node-ytsr#118]
`
[
  {
    "showingResultsForRenderer": {
      "showingResultsFor": {
        "runs": [
          {
            "text": "Showing results for"
          }
        ]
      },
      "correctedQuery": {
        "runs": [
          {
            "text": "اغنيه خلني "
          },
          {
            "text": "اصورك",
            "italics": true
          }
        ]
      },
      "correctedQueryEndpoint": {
        "clickTrackingParams": "CLUBEPAwGAAiEwjd8KOunubvAhWlNkwKHZFaC0A=",
        "commandMetadata": {
          "webCommandMetadata": {
            "url": "/results?search_query=%D8%A7%D8%BA%D9%86%D9%8A%D9%87+%D8%AE%D9%84%D9%86%D9%8A+%D8%A7%D8%B5%D9%88%D8%B1%D9%83",
            "webPageType": "WEB_PAGE_TYPE_SEARCH",
            "rootVe": 4724
          }
        },
        "searchEndpoint": {
          "query": "اغنيه خلني اصورك"
        }
      },
      "searchInsteadFor": {
        "runs": [
          {
            "text": "Search instead for"
          }
        ]
      },
      "originalQuery": {
        "simpleText": "اغنيه خلني اصوره"
      },
      "originalQueryEndpoint": {
        "clickTrackingParams": "CLUBEPAwGAAiEwjd8KOunubvAhWlNkwKHZFaC0A=",
        "commandMetadata": {
          "webCommandMetadata": {
            "url": "/results?search_query=%D8%A7%D8%BA%D9%86%D9%8A%D9%87+%D8%AE%D9%84%D9%86%D9%8A+%D8%A7%D8%B5%D9%88%D8%B1%D9%87&sp=QgIIAQ%253D%253D",
            "webPageType": "WEB_PAGE_TYPE_SEARCH",
            "rootVe": 4724
          }
        },
        "searchEndpoint": {
          "query": "اغنيه خلني اصوره",
          "params": "QgIIAQ%3D%3D"
        }
      },
      "trackingParams": "CLUBEPAwGAAiEwjd8KOunubvAhWlNkwKHZFaC0A="
    }
  },
  {
    "originalQuery": "اغنيه خلني اصوره",
    "correctedQuery": "اغنيه خلني اصوره",
    "results": 1923,
    "activeFilters": [],
    "refinements": [],
    "items": [],
    "continuation": null
  }
]
`

**Comment by TimeForANinja** [comment]
thanks for opening the issue
i tried it on master and it seems to work (now)
so check if you're using the latest version 😉
