### ISSUE TITLE
Stringifying continuation makes it invalid

### ISSUE THREAD

**Issue by losnappas** [TimeForANinja/node-ytsr#138]
Running `JSON.stringify` on the result object turns `Infinity` into `null`, which then gets run against this: https://github.com/TimeForANinja/node-ytsr/blob/master/lib/main.js#L125 .

And funnily enough, `(!isNaN(null) && isFinite(null)) === true`, so then the `continueReq` method throws. Let's add a check against null to check it?

**Comment by TimeForANinja** [comment]
👍 fix merged to git
unfortunately can't push it to npm atm
