### ISSUE TITLE
type compactPromotedItemRenderer is not known

### ISSUE THREAD

**Issue by lukect1212** [TimeForANinja/node-ytsr#140]
Hi, anything I can do about this? Thanks :)

**Comment by TimeForANinja** [comment]
The full error should link you a dump file
Can you provide it?

**Comment by lukect1212** [comment]
[fkrt6t8a8j-1628729034330.txt](https://github.com/TimeForANinja/node-ytsr/files/6972112/fkrt6t8a8j-1628729034330.txt)

**Comment by lukect1212** [comment]
[fkrt6t8a8j-1628729034330.txt](https://github.com/TimeForANinja/node-ytsr/files/6972148/fkrt6t8a8j-1628729034330.txt)

**Comment by lukect1212** [comment]
I get that, when command is set too 1 Parameter, and no response at all when it's set to multiple parameters. API key is valid, if I remove, bot log asks for it. If it's all in and good, I get nothing after the "search yt" command

**Comment by TimeForANinja** [comment]
thanks for providing the file 😉 
should be fixed
