### ISSUE TITLE
Limit becomes useless if pages option is set

### ISSUE THREAD

**Issue by VlaDexa** [TimeForANinja/node-ytsr#145]
It seeams that the library ignores the limit for items, if you set both limit and pages option

**Comment by TimeForANinja** [comment]
yep, that behaviour is wanted
as stated in the readme:
`pages[Number] -> limits the pulled pages [...] overwrites limit`

i don't see the point in using both `pages` and `limit` together

if you do require some more complex configurations you can always use `ytsr.continueReq`
