### ISSUE TITLE
Performance of search queries

### ISSUE THREAD

**Issue by miniwa** [TimeForANinja/node-ytsr#157]
I ran a simple performance test (see footer) on my fairly high-end machine. For 25 requests the average response time for a query was ~3.4 seconds and each request seemed pretty stable around that number (no outliers).
* Are these kinds of times to be expected?
* In your experience, what can be done to improve performance?

Versions:
> ytsr: v3.6.0
> node: v16.14.1
> OS: Win 10 x64

Test source:
```typescript
import * as ytsr from "ytsr";

const REQ_COUNT = 25;

async function main() {
  const times = [];
  for (let i = 0; i < REQ_COUNT; i++) {
    const start = performance.now();
    const result = await ytsr("business eminem explicit");
    const duration = performance.now() - start;
    console.log(`Request ${i + 1} took ${duration}ms`);
    times.push(duration);
  }

  // Results.
  let total = 0;
  times.forEach((time) => (total += time));
  const avgTime = total / REQ_COUNT;
  console.log(`AvgTime = ${avgTime}ms`);
}

main();
```

**Comment by TimeForANinja** [comment]
in general there is little to none computation done locally
even a pi should perform decent with this library
most time is simply wasted waiting for web requests

if you wanna improve performance
a) check your internet ping & bandwith
b) do requests in parallel
c) use the `pages` option (with the default limit 100 you're doing ~4 requests per ytsr call all sequentially...)
