### ISSUE TITLE
Search no longer returning results

### ISSUE THREAD

**Issue by MrRedacted** [TimeForANinja/node-ytsr#159]
It seems as though the tool is no longer returning results for many searches. It is almost as though there are problems with specifically music searches. Is anyone else noticing this issue? When searching for music I will typically get an empty search results items array.

**Comment by warior456** [comment]
i seem to not get responses to only links

**Comment by TimeForANinja** [comment]
can you provide example queries that return no results?

**Comment by MrRedacted** [comment]
"shinedown planet zero" as well as other variations such as "planet zero shinedown", etc. is the only example off the top of my head that I am currently unable to get results back for.

"coding music" was not working when I submitted this issue, as well as other music queries. That being said, those queries seem to be working now.

I am not sure if maybe this was an odd, temporary, one-off issue that was something caused by something YouTube is/was doing on their end?

**Comment by MrRedacted** [comment]
Noticed that this issue has become worse since my last comment a few days ago. Most music-related searches are coming back with nothing. Don't want to assume it's YouTube, but I'm going to assume it's YouTube. This repo has worked flawlessly for me, and continues to work perfectly for any searches that aren't music-related. Or maybe I'm just crazy lol.

**Comment by TimeForANinja** [comment]
the problem i'm having is that i can't reproduce this problem
i tried the queries multiple times, every few days and always received some results
what you could do is have a look at the parsing yourself or provide my with the body from [here](https://github.com/TimeForANinja/node-ytsr/blob/master/lib/main.js#L15)
