### ISSUE TITLE
Error: type chipCloudRenderer is not known

### ISSUE THREAD

**Issue by th0m4s** [TimeForANinja/node-ytsr#162]
It looks like there is a new type of element that the library cannot parse for the moment.
It's named `chipCloudRenderer` and doesn't happen to includes any important information as they may be links to subsets of the results.
For this example, with the query *Lithium Nirvana*, the chips said *Slowed*, *Acoustic* or *Guitar lessons* (see dump file).

If there is no plan to use these subsets (at least for the moment as they don't appear in every response), I can open a pull request to ignore them.

[qixmgfenvd-1650906170921.txt](https://github.com/TimeForANinja/node-ytsr/files/8556681/qixmgfenvd-1650906170921.txt)

**Comment by TimeForANinja** [comment]
thanks for the issue and file 👍 
i agree, added it to the ignore-List
