### ISSUE TITLE
Playlist results do not contain valid links

### ISSUE THREAD

**Issue by triggerhurt** [TimeForANinja/node-ytsr#17]
Line 85 in lib/util.js is the culprit:
const cleanID = exports.removeHtml(exports.between(string, 'data-list-id="', '"'));
Changing it to this seems to fix the problem:
const cleanID = exports.removeHtml(exports.between(string, 'href="/playlist?list=', '"'));

**Comment by TimeForANinja** [comment]
* tested
* confirmed the problem
* confirmed the solution helped
* happily implemented in https://github.com/TimeForANinja/node-ytsr/commit/c6dd72a05d41b6531083532b5f5ee2b9a9086579

Thanks a lot
