### ISSUE TITLE
Substitute HTTPS with fetch

### ISSUE THREAD

**Issue by EddieEJ** [TimeForANinja/node-ytsr#18]
Hello. I have been trying to implement this into my React Native app. However, I've been struggling with changing the getPage method since it uses `require('https')`.

I have tried to substitute it with the following, however unsuccessfully:
```
export const getPage = (ref, cb) => {
    fetch(ref)
    .then((response) => response.json())
    .then((resp) => {
        cb(null, resp);
    })
    .catch((err) => "Error:", err)
};
```
Could you provide some feedback on how I can replicate the exact output that `https.get` would return but by using `fetch`?

**Comment by TimeForANinja** [comment]
Sorry, but can't help you with React related stuff.

**Comment by EddieEJ** [comment]
Oh. I just wanted to ask then: is everything that HTTPS.get request for getPage do is to obtain the complete raw source code in a string format?

**Comment by TimeForANinja** [comment]
yep
`util.getPage(link, callback)` resolves by calling the callback with the response body as a string
