### ISSUE TITLE
failed at func parseItem: Cannot read properties of undefined (reading 'reelPlayerHeaderRenderer')

### ISSUE THREAD

**Issue by blackparader** [TimeForANinja/node-ytsr#183]
os: win32-x64, node.js: v18.12.1, ytsr: 3.8.0
[chnl42ouw-1679493304749.txt](https://github.com/TimeForANinja/node-ytsr/files/11040755/chnl42ouw-1679493304749.txt)

**Comment by LielXD** [comment]
It still return the data so to stop the dumps and the log spam I just deleted lines 95 - 107 in the "catchAndLogFunc" function (after catch)

**Comment by TimeForANinja** [comment]
dupe of #174
