### ISSUE TITLE
Dump error, music error as well. 

### ISSUE THREAD

**Issue by Luminityq** [TimeForANinja/node-ytsr#193]
For some reason it shows this and there is an issue with playing music as well and above this error thing on replit is a bunch of other errors
![2023-04-07 (10)](https://user-images.githubusercontent.com/122408285/230672286-e263e408-68fa-4710-bf86-b12a1b8b4104.png)

**Comment by eugabrielsilva** [comment]
Same. Had to switch over to [youtube-sr](https://github.com/skdhg/youtube-sr) while waiting for a fix

**Comment by TimeForANinja** [comment]
closed since the issue is missing the debug file mentioned in the error
