### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Missing catch or finally after try')

### ISSUE THREAD

**Issue by EclipseGame18** [TimeForANinja/node-ytsr#194]
I got this error when trying to play music using discord-music-player. i don't know how I got the error.

**Comment by FadelesSpade** [comment]
I got this error from ytdl-core. I'm not sure you're using ytdl-core as you mention discord-music-player, but discord-music-player could also be using it. There is a fix that will probably be added next update, but you can go ahead and do it now.
go to the file: ...node_modules\ytdl-core\lib\untils.js

Go to line 63, it should look like this.
![image](https://user-images.githubusercontent.com/42529233/230835090-ce0c72a6-c412-4cd8-a70f-17d02926ed6a.png)
Add the red underlined forward slash as seen in the image above and save.
The problem should be resolved.

**Comment by Klairm** [comment]
yes the error is from ytdl-core, the fix in a comment from here fixed my issue https://github.com/fent/node-ytdl-core/issues/1207

**Comment by TimeForANinja** [comment]
fixed with https://github.com/fent/node-ytdl-core/pull/1203
