### ISSUE TITLE
Cannot read properties of undefined (reading `browseEndpoint`)

### ISSUE THREAD

**Issue by Explosion-Scratch** [TimeForANinja/node-ytsr#195]
```
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in /Users/me/dir/node_modules/.pnpm/ytsr@3.8.2/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: darwin-arm64, node.js: v19.8.1, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************\
```

Not sure what's going on here. It does this somewhat randomly, not sure why. Looking at the dumps it looks like it's not handling YouTube movies and live streams.

[enc3rahqld-1681601250049.txt](https://github.com/TimeForANinja/node-ytsr/files/11240885/enc3rahqld-1681601250049.txt)
[h3qa3ug3mg-1681601249826.txt](https://github.com/TimeForANinja/node-ytsr/files/11240886/h3qa3ug3mg-1681601249826.txt)
[paxytmely-1681601249423.txt](https://github.com/TimeForANinja/node-ytsr/files/11240887/paxytmely-1681601249423.txt)

**Comment by s3849606** [comment]
I have the same issue

**Comment by Explosion-Scratch** [comment]
No unstale
