### ISSUE TITLE
Unknown type movie-vertical-poster

### ISSUE THREAD

**Issue by Pitasi** [TimeForANinja/node-ytsr#2]
Hi there!
I'm trying to use this so useful library, with some searches my app crash with:
`Error: unknown type |movie-vertical-poster|`

Wouldn't be possible to just ignore new types instead of throwing?

Thank you.

**Comment by TimeForANinja** [comment]
haven't rly thought about why im doing it like that ^^
guess ill change it to:
- log a clear message
- save a dumb a file

**Comment by TimeForANinja** [comment]
fixed in https://github.com/TimeForANinja/node-ytsr/commit/e86b15afe8a7c82958779bb5d30f8a5a17ddcf83
