### ISSUE TITLE
TypeError: filterWrapper is not iterable

### ISSUE THREAD

**Issue by nukeop** [TimeForANinja/node-ytsr#206]
Started occurring on pretty much every search. The error is thrown in `ytsr/lub/utils:23`, called by the `getFilters` function.

**Comment by nukeop** [comment]
On further debugging, it looks like `wrapper.subMenu.searchSubMenuRenderer` doesn't have the `groups` attribute sometimes.

**Comment by sdasda7777** [comment]
Yeah, I keep getting this error, while it doesn't seem to really appear at all for other users. Could the search be blocked outside the US, perhaps?

**Comment by rfcrocha** [comment]
I'm trying ytsr for the first time and finding the same issue

**Comment by nukeop** [comment]
I mitigated it somewhat simply by applying exponential backoff with 3 retries. There are still times when it fails though.

**Comment by athammer** [comment]
might be the same issue here. You might want to go into the node_modules of your project and manually change it till the owner can put in a fix 

https://github.com/TimeForANinja/node-ytsr/issues/180

**Comment by Zer0ne83** [comment]
As above, C is not iterable at i.parseFilters... Approx 1/30 requests actually work/return results. Time/delay between requests (including 24 hours+) makes no difference. I am also outside US (ref @sdasda7777's question). Will update if using US localized IP solves the issue.

**Comment by noviardi1986** [comment]
I think the issue is nothing to do with ytsr, it is rejected by youtube. And returned nothing.

**Comment by SeiRann** [comment]
i have run the filterWrapper code thru chatgpt and it give a safety check for the filterWrapper 
`const filterWrapper = ((wrapper.subMenu || wrapper.submenu)?.searchSubMenuRenderer || {}).groups || [];
`
here's the full explanation:
The code you provided seems to be a JavaScript module that exports a function `parseFilters(json)` to parse and extract filter information from a JSON object. The function appears to be used in a search-related context, possibly to parse YouTube search results.

As for non-iterable errors, this code should not produce any non-iterable errors on its own. It seems to be using various iterators like `for...of` loops to traverse arrays and objects, which are appropriate methods for iterating over iterable data structures in JavaScript.

However, there is one potential issue with the code. Specifically, the line:

```javascript
const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups;
```

It's possible that this line could throw a TypeError if neither `wrapper.subMenu` nor `wrapper.submenu` is defined, or if the resulting `searchSubMenuRenderer` is not an object with a `groups` property. To avoid this potential issue, you may want to add some checks or defensive coding to ensure that the data you're accessing exists before attempting to iterate over it.

For example, you can modify the line as follows to add a safety check:

```javascript
const filterWrapper = ((wrapper.subMenu || wrapper.submenu)?.searchSubMenuRenderer || {}).groups || [];
```

This change ensures that `filterWrapper` will always be an array, even if `wrapper.subMenu` and `wrapper.submenu` are undefined or don't have the expected properties.

Other than this, the code looks fine and should work as intended, provided that the input JSON object (`json`) has the expected structure and properties.

**Comment by Fennix900** [comment]
> i have run the filterWrapper code thru chatgpt and it give a safety check for the filterWrapper which seems to fix the issue `const filterWrapper = ((wrapper.subMenu || wrapper.submenu)?.searchSubMenuRenderer || {}).groups || []; ` here's the full explanation: The code you provided seems to be a JavaScript module that exports a function `parseFilters(json)` to parse and extract filter information from a JSON object. The function appears to be used in a search-related context, possibly to parse YouTube search results.
> 
> As for non-iterable errors, this code should not produce any non-iterable errors on its own. It seems to be using various iterators like `for...of` loops to traverse arrays and objects, which are appropriate methods for iterating over iterable data structures in JavaScript.
> 
> However, there is one potential issue with the code. Specifically, the line:
> 
> ```js
> const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups;
> ```
> 
> It's possible that this line could throw a TypeError if neither `wrapper.subMenu` nor `wrapper.submenu` is defined, or if the resulting `searchSubMenuRenderer` is not an object with a `groups` property. To avoid this potential issue, you may want to add some checks or defensive coding to ensure that the data you're accessing exists before attempting to iterate over it.
> 
> For example, you can modify the line as follows to add a safety check:
> 
> ```js
> const filterWrapper = ((wrapper.subMenu || wrapper.submenu)?.searchSubMenuRenderer || {}).groups || [];
> ```
> 
> This change ensures that `filterWrapper` will always be an array, even if `wrapper.subMenu` and `wrapper.submenu` are undefined or don't have the expected properties.
> 
> Other than this, the code looks fine and should work as intended, provided that the input JSON object (`json`) has the expected structure and properties.



Got the same error.
This solution fixed it for me. 
I replaced line 21 in the utils.js with the solution.

**Comment by Michal-Szczepaniak** [comment]
Confirmed here (outside us), fix works.

Damn… AI be outsmarting us

**Comment by nukeop** [comment]
It only hides the problem. It stops the function from crashing, but returns no results. So that's no fix. Pasting stuff into chatgpt without thinking is not a solution to anything.

**Comment by Michal-Szczepaniak** [comment]
But i got results just fine, though i agree with latter, the fix does indeed work

**Comment by Fennix900** [comment]
Maybe, but i got this error and after replacing the line i got the results

**Comment by nukeop** [comment]
How? That "fix" only returns an empty list if both scraped elements are undefined.

**Comment by Fennix900** [comment]
> How? That "fix" only returns an empty list if both scraped elements are undefined.

Idk, i only know that i got always errors when starting the query and with this "fix" i got results

**Comment by nukeop** [comment]
Then those results are wrong, because you're not applying any filters.

**Comment by Michal-Szczepaniak** [comment]
Because I am not using filters perhaps? From what i see it will return results but not filters, it doesn't prevent results from returning

**Comment by Fennix900** [comment]
> Because I am not using filters perhaps? From what i see it will return results but not filters, it doesn't prevent results from returning
> 
> whats wrong with not using filters?
> 
> Ok so it's not "proper" fix but it does return results if filters are not used, thats what we can agree on

Agreed, as far as i can tell i get the results i expected or at least the results that i require to work with

**Comment by rjdg14** [comment]
> > i have run the filterWrapper code thru chatgpt and it give a safety check for the filterWrapper which seems to fix the issue `const filterWrapper = ((wrapper.subMenu || wrapper.submenu)?.searchSubMenuRenderer || {}).groups || []; ` here's the full explanation: The code you provided seems to be a JavaScript module that exports a function `parseFilters(json)` to parse and extract filter information from a JSON object. The function appears to be used in a search-related context, possibly to parse YouTube search results.
> > As for non-iterable errors, this code should not produce any non-iterable errors on its own. It seems to be using various iterators like `for...of` loops to traverse arrays and objects, which are appropriate methods for iterating over iterable data structures in JavaScript.
> > However, there is one potential issue with the code. Specifically, the line:
> > ```js
> > const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's possible that this line could throw a TypeError if neither `wrapper.subMenu` nor `wrapper.submenu` is defined, or if the resulting `searchSubMenuRenderer` is not an object with a `groups` property. To avoid this potential issue, you may want to add some checks or defensive coding to ensure that the data you're accessing exists before attempting to iterate over it.
> > For example, you can modify the line as follows to add a safety check:
> > ```js
> > const filterWrapper = ((wrapper.subMenu || wrapper.submenu)?.searchSubMenuRenderer || {}).groups || [];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This change ensures that `filterWrapper` will always be an array, even if `wrapper.subMenu` and `wrapper.submenu` are undefined or don't have the expected properties.
> > Other than this, the code looks fine and should work as intended, provided that the input JSON object (`json`) has the expected structure and properties.
> 
> Got the same error. This solution fixed it for me. I replaced line 21 in the utils.js with the solution.

Can you tell me where utils.js file that you're talking about is? FreeTube is no doubt in need of an update and I have it installed on my computer with this very problem (which has been occuring for several months), yet I can't find the file you're talking about anywhere in my installation (it's a user-side installation in the Windows AppData folder).

**Comment by SeiRann** [comment]
node_modules/ytsr/lib/utils.js

**Comment by Michal-Szczepaniak** [comment]
Isn't this fixed by https://github.com/TimeForANinja/node-ytsr/pull/203?
