### ISSUE TITLE
TypeError thrown from util's removeHtml() when parsing YouTube movies

### ISSUE THREAD

**Issue by slothiful** [TimeForANinja/node-ytsr#21]
**Issue:** When an "official" YouTube movie ([YouTube Movies](https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g)) is returned by the search query, the TypeError below is thrown and it can't be caught.

**Error:**
```js
/home/w1tch/Bot/node_modules/ytsr/lib/util.js:177
     director: exports.removeHtml(filmMeta.split('<li>')[2].replace(/<[^>]+>|^[^:]+: /g, '')),
                                                           ^
 TypeError: Cannot read property 'replace' of undefined
     at Object.exports.parseMovie (/home/w1tch/Bot/node_modules/ytsr/lib/util.js:177:59)
     at Object.exports.parseItem (/home/w1tch/Bot/node_modules/ytsr/lib/util.js:40:20)
     at /home/w1tch/Bot/node_modules/ytsr/lib/main.js:47:22
     at Array.map (<anonymous>)
     at /home/w1tch/Bot/node_modules/ytsr/lib/main.js:47:8
     at IncomingMessage.<anonymous> (/home/w1tch/Bot/node_modules/ytsr/lib/util.js:249:7)
     at IncomingMessage.emit (events.js:215:7)
     at endReadableNT (_stream_readable.js:1183:12)
     at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Reproduction:** The query that originally caused this error was "Monsters, Inc." (while searching for meme music).
```js
require('ytsr')('monsters inc'); // same results, naked or not
```

**Environment:**
> Ubuntu 18.04
> Node.js v12.11.1
> `ytsr` 6.13.0

**Comment by TimeForANinja** [comment]
can't replicate on my machine...
noticed that i get the German version of the page, which shouldn't happen...

**Comment by slothiful** [comment]
After some investigating, it seems that some YouTube Movies omit the director from the film metadata. `filmMeta` in the `parseMovie()` function unexpectedly has no director within the list in this case.

Problematic `filmMeta`:
```
<li>Actors: Billy Crystal, John Goodman, Steve Buscemi</li>
```

This result is from [this movie](https://www.youtube.com/watch?v=-2n6esRBs2k), which doesn't have a director specified.

**Comment by TimeForANinja** [comment]
Can you do me a favor and tell me whether https://github.com/TimeForANinja/node-ytsr/tree/optional_director solves your problem?

**Comment by slothiful** [comment]
That branch works perfectly. Thank you!

**Comment by TimeForANinja** [comment]
Nice.
Thanks for letting me know.
Should be on npm, too.
