### ISSUE TITLE
Get likes dislikes count

### ISSUE THREAD

**Issue by vasyl-shumskyi** [TimeForANinja/node-ytsr#25]
Thanks for the awesome module! 

It would be really awesome if we can get likes / dislikes count for every video.

**Comment by TimeForANinja** [comment]
unfortunately, this module can only provide you with the data you see when you do a search in your browser, which (at least for me) doesn't provide likes / like ratios...

**Comment by vasyl-shumskyi** [comment]
Thanks for letting me know. I thought likes / dislikes are on the same scope as `views` count that module returns.

**Comment by vasyl-shumskyi** [comment]
Hey @TimeForANinja looks like likes count is shown now when to do a search.

Check out the attached screenshot:

![Screen Shot 2019-12-20 at 21 29 01](https://user-images.githubusercontent.com/2331802/71287149-33c3ca00-2370-11ea-9e06-030a800877f5.png)

**Comment by TimeForANinja** [comment]
:thinking: can't replicate

**Comment by TimeForANinja** [comment]
the likes got to do with being logged in
closing since it's not possible with the current backend
