### ISSUE TITLE
Issue with live video content

### ISSUE THREAD

**Issue by venkataramanab** [TimeForANinja/node-ytsr#31]
Incorrect data at views, uploaded_at, duration fields for live content. 
I'm attaching the sample response below.

![Screenshot 2020-03-10 at 2 04 55 PM](https://user-images.githubusercontent.com/15572489/76294223-785c6300-62d8-11ea-8bc7-48c9dfc844fa.png)

**Comment by venkataramanab** [comment]
That's really quick @TimeForANinja .
I did created the same commit.

**Comment by venkataramanab** [comment]
#32

**Comment by TimeForANinja** [comment]
sometimes you get lucky 😉 
thanks for mentioning thou
