### ISSUE TITLE
Missing safe search results

### ISSUE THREAD

**Issue by venkataramanab** [TimeForANinja/node-ytsr#34]
@TimeForANinja I need a safe search option for results. But currently, I didn't see an option for that.
It really helps people who need to filter out safe results. Is there any workaround for this?

**Comment by TimeForANinja** [comment]
Is there a safe search option in the browser?

**Comment by venkataramanab** [comment]
Yes, It is.
Please take a look at the below images.

![Screenshot 2020-03-12 at 10 37 49 PM](https://user-images.githubusercontent.com/15572489/76547004-7c43dd00-64b2-11ea-9ffc-d9a8f8259f58.png)
![Screenshot 2020-03-12 at 10 37 58 PM](https://user-images.githubusercontent.com/15572489/76546887-4272d680-64b2-11ea-8786-b69726b99a87.png)

**Comment by TimeForANinja** [comment]
try setting the `PREF=f2=8000000` cookie via the header

**Comment by venkataramanab** [comment]
I'm getting the same response even after setting cookie. It's working well in browser but when I set the same cookie on `https` no change in response.

sample code:
`
const request = HTTPS.get(ref, { Cookie: 'PREF=f2=8000000;' }, resp => { /* code */})
`

**Comment by venkataramanab** [comment]
Nice, It worked. Can I set an option for a safe search and make PR?

**Comment by TimeForANinja** [comment]
sure, why not 😉
