### ISSUE TITLE
Fix channel subscriber count

### ISSUE THREAD

**Issue by Snazzah** [TimeForANinja/node-ytsr#36]
It seems like there used to be a way of getting an exact subscriber count before the count change, but now all `followers` fields are 0. You could probably just have it be a string (i.e. `"5.52M"`) or parse it into an estimate number.
```js
{
  type: 'channel',
  name: 'Fitz',
  channel_id: 'UCtb8P4rf_1n8KS8eZk_lNNw',
  link: 'https://www.youtube.com/channel/UCtb8P4rf_1n8KS8eZk_lNNw',
  avatar: 'https://yt3.ggpht.com/a/AATXAJzK8HUDztEw5PfBCjDJz26HxbrfrxwAmaxCjg=s176-c-k-c0x00ffffff-no-rj-mo',
  verified: true,
  followers: 0,
  description_short: "I don't upload very much, but when I do it's always the best.",
  videos: 150
}
```

**Comment by TimeForANinja** [comment]
i am actually not finding this information in the response anymore...

**Comment by Snazzah** [comment]
What information are you referring to?

**Comment by TimeForANinja** [comment]
the `5.52M` follower string
it's not present in the response from youtube

**Comment by Snazzah** [comment]
Should be with a `subscribers` id
```
<span id="subscribers" class="style-scope ytd-channel-renderer">5.52M subscribers</span>
```

**Comment by TimeForANinja** [comment]
should be...
`<htmlbody>.toUpperCase().indexOf('52M')` returned `-1` for the hole page

**Comment by Snazzah** [comment]
Yeah I can't seem to get it either
