### ISSUE TITLE
Getting Next video 

### ISSUE THREAD

**Issue by batuhansahan** [TimeForANinja/node-ytsr#39]
when we click next button youtube shows similar or whatever video is there a solution with this library or can it be done

**Comment by TimeForANinja** [comment]
ytsr uses an endpoint differing from what you see when searching via there website - as far as i know that would require a complete rework of the library

**Comment by SuspiciousLookingOwl** [comment]
You can try my lib: [youtubei](https://www.npmjs.com/package/youtubei)

use [`.getVideo()`](https://youtubei.netlify.app/docs/api/classes/client#getvideo) method then access [`.upNext`](https://youtubei.netlify.app/docs/api/classes/video#upnext) or [`.related`](https://youtubei.netlify.app/docs/api/classes/video#related) from the returned [`Video`](https://youtubei.netlify.app/docs/api/classes/video) object

**Comment by TimeForANinja** [comment]
closing this since it is not relevant for this library
still thanks for opening an issue
might be able to implement in node-ytdl-core, which does already fetch the video page & player

if you don't agree feel free to comment again / open the issue again
