### ISSUE TITLE
Not works with React Native

### ISSUE THREAD

**Issue by b3rkaydem1r** [TimeForANinja/node-ytsr#42]
![photo_2020-05-14_13-48-07](https://user-images.githubusercontent.com/35340093/81925786-a36d7680-95e9-11ea-90aa-95c0b6f366b7.jpg)
When i define const ytsr = require('ytsr');
It returns;
path could not be found within the project.

**Comment by b3rkaydem1r** [comment]
i fix that with npm install path
but there is new error.
npm install https doesnt fix.
and https library doesnt have index.js
![image](https://user-images.githubusercontent.com/35340093/81933830-a6229880-95f6-11ea-810b-a336ed5d5d09.png)

**Comment by TimeForANinja** [comment]
those are the modules build into node.js
never used react but i bet somewhere is a guide on how to get native node.js modules to work in react

**Comment by akinozgen** [comment]
working with nodejs modules on react is real pain. i suggest you build a server and use it in server. then implement a communication with your app to server.

**Comment by Immortalin** [comment]
@b3rkaydem1r from what I can tell, those dependencies are mostly used for debugging, see `util.js`. Just make a fork and remove those lines and it should work.

**Comment by b3rkaydem1r** [comment]
Thank you for your help @Immortalin 
i use node-libs-react-native and react-native-fs
but I'm facing a new mistake.
```
ytsr('dua lipa', function(err, searchResults) {
       if(err) throw err;
      console.log(searchResults)
});
```
I get an error when I try to use the library.
![image](https://user-images.githubusercontent.com/35340093/86512057-34e9af80-be07-11ea-86df-d1fecfce21d0.png)

**Comment by Immortalin** [comment]
Did you add the react-native node libs globals?

**Comment by b3rkaydem1r** [comment]
![image](https://user-images.githubusercontent.com/35340093/86512103-b2152480-be07-11ea-9e5f-15c26a38a9e1.png)
![image](https://user-images.githubusercontent.com/35340093/86512106-b93c3280-be07-11ea-9b15-41aa26bcef78.png)
what else will i add?

**Comment by b3rkaydem1r** [comment]
have you any idea?

**Comment by naugtur** [comment]
This is not the right place to solve this. 
You should try stackoverflow.com 

Your issue is not with node-ytsr anyway and the people who hang out here are unlikely to be experienced with react native.

**Comment by TimeForANinja** [comment]
> This is not the right place to solve this.
> You should try stackoverflow.com
> 
> Your issue is not with node-ytsr anyway and the people who hang out here are unlikely to be experienced with react native.

i must agree

**Comment by sarmadkamal464** [comment]
@TimeForANinja by using patching can I sue it directly?
