### ISSUE TITLE
nextpageRef returns null for all searches

### ISSUE THREAD

**Issue by PrestonN** [TimeForANinja/node-ytsr#47]
When performing a search, the `nextpageRef` variable is returning null no matter what type of search I make.  This seems to be a recent issue as I haven't had this problem in the past.  It's possible that YouTube might have slightly changed their layout.

Thanks for the help.

**Comment by TimeForANinja** [comment]
🤔 yep
it's a problem with how i move to special positions in the html
still hesitant on whether sth like cheerio is a better choice

**Comment by TimeForANinja** [comment]
solved with https://github.com/TimeForANinja/node-ytsr/commit/8c0d2425fda742f50f69fedefb3276f1975f0f81

**Comment by PrestonN** [comment]
Hello again!

Seems like this issue has come back.  Not sure if you were aware of it, but it didn't seem appropriate to make a new issue about it.
