### ISSUE TITLE
TypeError: "listener" argument must be a function

### ISSUE THREAD

**Issue by lxcool9243** [TimeForANinja/node-ytsr#49]
I am using this library for some basic search which is working fine on aws servers and localhost as well but getting issue when deploying to firebase functions. Below is my code

```
        ytsr.getFilters(key, (error, filters) => {
            if (error) {
                return res.json({
                    error: "Error Occured : " + error
                });
            }

            filter = filters.get("Type").find((o) => o.name.startsWith("Video"));

            return ytsr(
                null, {
                    limit: limit,
                    nextpageRef: filter.ref,
                },
                (error, results) => {
                    if (error) {
                        return res.json({
                            error: "Error Occured : " + error
                        });
                    }

                    return res.json(results);
                }
            );
        });
```

Attaching screenshot as well

![Annotation 2020-06-12 224251](https://user-images.githubusercontent.com/35449781/84528859-114ab200-acfe-11ea-8f91-8c22ab4d1906.png)

**Comment by lxcool9243** [comment]
I think the issue is with the firebase spark plan. They restrict external connections due to non billing account.

**Comment by TimeForANinja** [comment]
not exactly
it has to do with a change in node's api - see https://github.com/TimeForANinja/node-ytpl/issues/46 for more
unfortunately quite busy atm...

**Comment by barhemo** [comment]
@TimeForANinja can u reopen?

**Comment by TimeForANinja** [comment]
😉 sure can do
you can try the `rework`-branch
should be fixed there

**Comment by barhemo** [comment]
@TimeForANinja i have another problem there, 
![image](https://user-images.githubusercontent.com/56646489/88207619-bdb27900-cc58-11ea-803d-21e17b1ff2fa.png)

u know why?

**Comment by TimeForANinja** [comment]
> @TimeForANinja i have other problem in , `rework`-branch
> ![image](https://user-images.githubusercontent.com/56646489/88207619-bdb27900-cc58-11ea-803d-21e17b1ff2fa.png)
> 
> u know why?

🤔 can you provide me with some more information
can't replicate on my machine and tests passed

**Comment by barhemo** [comment]
@TimeForANinja 
![image](https://user-images.githubusercontent.com/56646489/88208340-bcce1700-cc59-11ea-9e87-5756dff1bd0e.png)
this is the parsed object.

when i use postman with https://www.youtube.com/watch?v=OHRog2ohHPI&hl=en&bpctr=1595095082&pbj=1 i also get the same object
![image](https://user-images.githubusercontent.com/56646489/88208665-41209a00-cc5a-11ea-8b8f-4453ebf7f537.png)

**Comment by TimeForANinja** [comment]
reminds me of https://github.com/TimeForANinja/node-ytpl/pull/64
=> cookies required to access

**Comment by barhemo** [comment]
@TimeForANinja my cookies are enabled..
what do u get from here? https://www.youtube.com/results?spf=navigate&gl=US&hl=en&search_query=hello
i get the reload:now object.
when i remove the spf i get youtube page with the results

**Comment by TimeForANinja** [comment]
the `spf=navigate` is a query for an older youtube layout
disabling it breaks the library...
unfortunately can't replicate

**Comment by barhemo** [comment]
maybe they blocked my country somehow

**Comment by barhemo** [comment]
@TimeForANinja more info how to replicate:
i used your package in frontend app (browserify), so probably it is cors problem. i fixed it by adding https://cors-anywhere.herokuapp.com to BASE_URL, and adding x-requested-with header. but if u can fix it, it will be good

**Comment by TimeForANinja** [comment]
🤔 i mean problems occur when you use modules out of their supported space
since i am not into browserify what i would offer you is add a point in the README for others to find

**Comment by TimeForANinja** [comment]
closing since fixed in rework
