### ISSUE TITLE
getFilters function is not in typings

### ISSUE THREAD

**Issue by Androz2091** [TimeForANinja/node-ytsr#53]
The `ytsr.getFilters()` function described [here](https://github.com/TimeForANinja/node-ytsr#ytsrgetfilterssearchstring-callback) is not present in the typings and can't be used with TypeScript.
Thank you for your work and I hope it can be fixed soon!

**Comment by TimeForANinja** [comment]
should find time in the next day or two
you would have to test it for me thou 😅
