### ISSUE TITLE
Two (three) dumps

### ISSUE THREAD

**Issue by MrZBou** [TimeForANinja/node-ytsr#56]
Hello, today I got 2 dumps while using ytsr. Unfortunately, I didn’t know what the problems they were entailing, because it appeared while other people were using my bot. Perhaps they have something you need, so at the 'request of your console error', I created this issue
```
/********************************************************************************************************************************************************************************************************
found an unknwon type |||
pls post the the files in ...node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
********************************************************************************************************************************************************************************************************\

```

(I also attached a dump two weeks ago)
[dumps.zip](https://github.com/TimeForANinja/node-ytsr/files/4954185/dumps.zip)

**Comment by TimeForANinja** [comment]
👍 shoud be fixed
thanks for letting me know
