### ISSUE TITLE
How can I get the URL of the very first video?

### ISSUE THREAD

**Issue by DaLLamaKing** [TimeForANinja/node-ytsr#57]
How can I get the URL of the very first video? Pretty much the question is the same as the title. I just want someone  to be able to use my code to find the very first song/video and be able to play it.

**Comment by TimeForANinja** [comment]
You can find an example output [here](https://github.com/TimeForANinja/node-ytsr/blob/master/example/example_search_output)

```ytsr(<search q>).then(resp => console.log(resp.items[0].link));```

**Comment by supertiger1234** [comment]
isnt there a way to safe bandwidth? Because we are getting so much data but we only need 1 item.

**Comment by TimeForANinja** [comment]
> isnt there a way to save bandwidth? Because we are getting so much data but we only need 1 item.

set the pages parameter to 1
