### ISSUE TITLE
How to suppress warning "support for callbacks will be removed in the next release"

### ISSUE THREAD

**Issue by d4sein** [TimeForANinja/node-ytsr#58]
Hey, I couldn't find a way to suppress this message, I also tried `ytsr.do_warn_deprecate = false`, but it had no effect.

**Comment by TimeForANinja** [comment]
🤔 
![image](https://user-images.githubusercontent.com/17046330/88487429-5ad91e80-cf85-11ea-84ab-449149cdf741.png)

there is another option which should do the trick but is not the prefered way
`ytsr(<searchString>, <options>, <callback>, true)`

**Comment by d4sein** [comment]
I saw that you made a commit to the repo, updating from 0.1.17 to 0.1.19 did it, thanks.
Also, you could've sent a message here notifying me of the change. 🤪
