### ISSUE TITLE
Change how HTTP requests are done to be compatible with stream-http

### ISSUE THREAD

**Issue by flaviotordini** [TimeForANinja/node-ytsr#64]
When trying to browserify ytsr, I noticed that the way ytsr makes http requests, while correct, is not supported by stream-http, the "shim" used by webpack and browserify to mimick the nodejs module.

I reported a bug to them: https://github.com/jhiesey/stream-http/issues/116

A small change would make it compatible. In utils.js, replace:
`const request = HTTPS.get(ref, options, resp => {`

With
```
options = Object.assign(URL.parse(ref), options);
const request = HTTPS.get(options, resp => {
```

Would that be ok for you?

**Comment by TimeForANinja** [comment]
actually - planned to roll out the rework this weekend, which uses miniget for the requests...
