### ISSUE TITLE
Select youtube country/region 

### ISSUE THREAD

**Issue by LucasAlda** [TimeForANinja/node-ytsr#69]
Hi! i want to get music search results based on argentina but when i push to heroku (usa) i get differents results

**Comment by TimeForANinja** [comment]
try setting the gl / hl options accordingly:
```js
ytsr('query', { gl: 'US', hl: 'en' })...
```
they default to [US and en](https://github.com/TimeForANinja/node-ytsr/blob/master/lib/util.js#L7)

**Comment by LucasAlda** [comment]
It works, thanks!
