### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by sayuribotbr** [TimeForANinja/node-ytsr#71]
Some searches are returning this error... probably something related to JSON.parse() function.

**Comment by TimeForANinja** [comment]
looks like a major rework from youtube's side
this are the new api-data i could pull from that page (if anyone cares to see)
[json.txt](https://github.com/TimeForANinja/node-ytsr/files/5320519/json.txt)

i know it's a problem that the library crashes but i'm unsure if it makes sense to adopt at fastest speed possible
this might lead to major changes and a lot of work

**Comment by dalisoft** [comment]
Same issue

**Comment by sayuribotbr** [comment]
None of my searches are working anymore because of this and I really need this library for my Discord Bot :(
If it is possible to fix it, I would be extremely grateful...

**Comment by JackyKit123** [comment]
Same issue, but the problem doesn't occur in a consistent way. Sometime the same search query and option pass while sometimes it doesn't

**Comment by thelastspark** [comment]
Would it be possible to have the current way and if it fails, attempt a more temporary duct-tape fix until we know for sure if the new API formatting will stay?

**Comment by MrZBou** [comment]
Same problem, 75% of requests returns this

**Comment by MoartMedia** [comment]
Same problem

**Comment by TimeForANinja** [comment]
started working on it in https://github.com/TimeForANinja/node-ytsr/tree/wip-api-adjustments but have problems finding the time

**Comment by 112batman** [comment]
same problem

**Comment by kira0x1** [comment]
ive been getting this alot and while testing I realized its arbitrary one minute it I get it one minute I dont

**Comment by flaviotordini** [comment]
Hi all, until the bug is fixed I suggest this work around: in your script/app when you receive this error, clear the cookies in your http connection and retry. Do this until you get a working search, then keep the cookies.

**Comment by lxcool9243** [comment]
> Hi all, until the bug is fixed I suggest this work around: in your script/app when you receive this error, clear the cookies in your http connection and retry. Do this until you get a working search, then keep the cookies.

How can I do this programmatically in an app running server side ?

**Comment by 1Conan** [comment]
Hello, here's what I use currently with the new update. Might help with updating this module :D
https://gist.github.com/1Conan/9446700b106759e7ba5dcad49dda4fc3

**Comment by TulioAbreu** [comment]
:crying_cat_face: I'm having the same issue. Do you have any tips on how to hotfix this running inside Node environment?

**Comment by TimeForANinja** [comment]
> started working on it in https://github.com/TimeForANinja/node-ytsr/tree/wip-api-adjustments but have problems finding the time

that's the only hotfix i can provide for now

**Comment by SoulHarsh007** [comment]
@TimeForANinja Have a look at <https://github.com/SoulHarsh007/youtube-scrape/blob/master/scraper.js>, I hope it helps you 😄

**Comment by cyph84** [comment]
Seems like its happening 100% of the time now

**Comment by TimeForANinja** [comment]
> Seems like its happening 100% of the time now

i'd count that as a good sign

**Comment by Siposattila** [comment]
Yeah the problem occurs 100% all the time... :c

**Comment by 1Conan** [comment]
https://gist.github.com/1Conan/9446700b106759e7ba5dcad49dda4fc3

What I currently use. hopefully it helps

**Comment by lxcool9243** [comment]
> > started working on it in https://github.com/TimeForANinja/node-ytsr/tree/wip-api-adjustments but have problems finding the time
> 
> that's the only hotfix i can provide for now

For now I am using YT Data API and waiting for this bug to resolve.

**Comment by kira0x1** [comment]
funny enough another API I found had a similar problem. If I get time ill try to help out.

**Comment by Klema4** [comment]
I have a similar problem too ngl. Is there a way to fix this faster than the devs? I don't want to wait another month :(

**Comment by dalisoft** [comment]
> I have a similar problem too ngl. Is there a way to fix this faster than the devs? I don't want to wait another month :(

Then help these devs to get fix faster

**Comment by kira0x1** [comment]
> > I have a similar problem too ngl. Is there a way to fix this faster than the devs? I don't want to wait another month :(
> 
> Then help these devs to get fix faster

They were asking if it was faster.

**Comment by kira0x1** [comment]
> I have a similar problem too ngl. Is there a way to fix this faster than the devs? I don't want to wait another month :(

It is, I think the dev said theyre short on time so if you can spend time on the repo that would be good ♥

**Comment by Klema4** [comment]
> > I have a similar problem too ngl. Is there a way to fix this faster than the devs? I don't want to wait another month :(
> 
> It is, I think the dev said they're short on time so if you can spend time on the repo that would be good ❤️

Ok thx, I will wait then.

**Comment by TimeForANinja** [comment]
> https://gist.github.com/1Conan/9446700b106759e7ba5dcad49dda4fc3
> 
> What I currently use. hopefully it helps
@1Conan 
is this https://gist.github.com/1Conan/9446700b106759e7ba5dcad49dda4fc3#file-youtube-ts-L23 sth that randomly appears?

**Comment by firsttobebear** [comment]
Is there an update on the status?

**Comment by Siposattila** [comment]
Nope! I will try to help the devs but I have to work sry this project where I need this lib is just a side project for my own satisfaction.

**Comment by 1Conan** [comment]
> > https://gist.github.com/1Conan/9446700b106759e7ba5dcad49dda4fc3
> 
> > 
> 
> > What I currently use. hopefully it helps
> 
> 
> 
> @1Conan 
> 
> is this https://gist.github.com/1Conan/9446700b106759e7ba5dcad49dda4fc3#file-youtube-ts-L23 sth that randomly appears?


For me, yes. The results seems to swap between those two. 

Though when I ran the bot in AU maybe a 3rd one got thrown in the mix since it breaks again sometimes lol.

**Comment by firsttobebear** [comment]
Any update?

**Comment by TimeForANinja** [comment]
try the wip: `npm i ytsr@wip`

**Comment by batuhansahan** [comment]
has any usage doc changed, because im getting "search string is mandatory" error. @TimeForANinja

**Comment by TimeForANinja** [comment]
Yep, quite a few things changed
Wip will end up in a new major release and I'll propably write some 'how to port' notes

For your use case I'd have to guess without more intel
My guess: if you use filters check the /test/e3e-test.js for changes 😉

**Comment by batuhansahan** [comment]
thanks for anyone want to use new api

```     
      const filters = await ytsr.getFilters("NoCopyrightMusic");
      const filter = filters.get('Type').find(a => a.label === 'Video');
      const search = await ytsr(filter.query, { limit: 25 });
      console.log(search);
```
