### ISSUE TITLE
ailed to parse Type pls post the the files in C:\Users\denys\Documents\GitHub\ShortAnswerDiscordBot\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues

### ISSUE THREAD

**Issue by thelastspark** [TimeForANinja/node-ytsr#79]
Since github doesn't support the .dumb file so I'll just give you a pastebin link.

1) https://pastebin.com/8VKS3NdR
2) https://pastebin.com/C2T90SH7

**Comment by TimeForANinja** [comment]
👍 thanks
fixed few seconds ago in WIP
