### ISSUE TITLE
Unknown Type

### ISSUE THREAD

**Issue by Peppy8651** [TimeForANinja/node-ytsr#83]
[1x0vmmi6op-1604694953485.txt](https://github.com/TimeForANinja/node-ytsr/files/5503431/1x0vmmi6op-1604694953485.txt)

That's the file I got above. Here is the console log I got;

/********************************************************************************************************************************************************************************************************
unknown type
pls post the the files in C:\Users\Owner\Documents\BirdyBirdy\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
********************************************************************************************************************************************************************************************************\

Today I got the console log above. I decided to follow the instructions in that console log.
Here is the text from the file if you don't want to download it:

`{
  "emergencyOneboxRenderer": {
    "title": {
      "simpleText": "Need help? In the United States"
    },
    "firstOption": {
      "singleActionEmergencySupportRenderer": {
        "actionText": {
          "simpleText": "Call 1-800-273-8255"
        },
        "navigationText": {
          "simpleText": "National Suicide Prevention Lifeline"
        },
        "navigationEndpoint": {
          "clickTrackingParams": "CIkBEK5qIhMI6qCaxeLu7AIVxs4WCR3JhwMp",
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "//www.youtube.com/redirect?event=&q=http%3A%2F%2Fwww.suicidepreventionlifeline.org%2F&usg=uo4JShNAAQJqdWnfYwxanQ",
              "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
              "rootVe": 83769
            }
          },
          "urlEndpoint": {
            "url": "//www.youtube.com/redirect?event=&q=http%3A%2F%2Fwww.suicidepreventionlifeline.org%2F&usg=uo4JShNAAQJqdWnfYwxanQ"
          }
        },
        "detailsText": {
          "simpleText": "Free · 24/7 · Confidential · In English, Spanish"
        },
        "icon": {
          "iconType": "PHONE"
        },
        "trackingParams": "CIkBEK5qIhMI6qCaxeLu7AIVxs4WCR3JhwMp"
      }
    },
    "secondOption": {
      "singleActionEmergencySupportRenderer": {
        "actionText": {
          "simpleText": "Text \"SAFE\" to 741-741"
        },
        "navigationText": {
          "simpleText": "Crisis Text Line"
        },
        "navigationEndpoint": {
          "clickTrackingParams": "CIgBEK5qIhMI6qCaxeLu7AIVxs4WCR3JhwMp",
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "//www.youtube.com/redirect?event=&q=http%3A%2F%2Fwww.crisistextline.org%2F&usg=GWWeuwrnAjTCSNf94JeGwQ",
              "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
              "rootVe": 83769
            }
          },
          "urlEndpoint": {
            "url": "//www.youtube.com/redirect?event=&q=http%3A%2F%2Fwww.crisistextline.org%2F&usg=GWWeuwrnAjTCSNf94JeGwQ"
          }
        },
        "detailsText": {
          "simpleText": "Free · 24/7 · Confidential"
        },
        "icon": {
          "iconType": "SMS"
        },
        "trackingParams": "CIgBEK5qIhMI6qCaxeLu7AIVxs4WCR3JhwMp"
      }
    },
    "trackingParams": "CIcBEK1qGAAiEwjqoJrF4u7sAhXGzhYJHcmHAyk="
  }
}`

**Comment by Peppy8651** [comment]
Ok since nobody is going to comment I will add a piece of information that I didn't add last time cuz I forgot. The search term was "suicide". The person who used this term was just looking for a song, so don't worry about it. If you search it up on YouTube an event appears as the first item which contains the info inside the json text in the issue.

**Comment by TimeForANinja** [comment]
😂 all fine
working in wip 👍
