### ISSUE TITLE
search return undefined

### ISSUE THREAD

**Issue by Zigecek** [TimeForANinja/node-ytsr#84]
Hello, I have a problem with searching. When I try to search something, always it will return undefined.

here is my code:

```
var res = await ytsr(args.join(' ')).catch(e => {
                    message.channel.send(':x: **Nothing found**');
                    return;
                });
```
"res" is always undefined.

I have all variables declared. (including ytsr)

Someone help me?

**Comment by TimeForANinja** [comment]
the way async/await works the catch statement is not stupping execution which means res is undefined and crashes the next line you do sth like `res.item[0]`

**Comment by Zigecek** [comment]
Oh, sorry, I just fixed it with using "ytdl" witch I'm using anyway.
