### ISSUE TITLE
Log Dump As Requested 

### ISSUE THREAD

**Issue by thelastspark** [TimeForANinja/node-ytsr#88]
Leaving paste bins for the logs found in the /dumps

https://pastebin.com/tW41HgRr
https://pastebin.com/30qE7e6r
https://pastebin.com/XrqFwa3y
https://pastebin.com/ZwUjwLDb
https://pastebin.com/Xy3EBgGx

**Comment by TimeForANinja** [comment]
thanks for the help 👍 
update should be available via git or the npm @wip tag
