### ISSUE TITLE
Does this module no longer works with URLs ?

### ISSUE THREAD

**Issue by Tenclea** [TimeForANinja/node-ytsr#94]
I used to do requests like :
`ytsr('https://www.youtube.com/watch?v=qEfPBt9dU60')`
and the promise keeps getting rejected with the following error : `Error: link has to include a "search_string" query`.

Was there some kind of API change, or are urls no loner supported ?

**Comment by TimeForANinja** [comment]
There was a major redesign with v2
Didn't think anyone would search for Video links
Any reason for doing so?

**Comment by Tenclea** [comment]
> Any reason for doing so?

Well, primarily to get the metadata of the video, or even related videos sometimes

**Comment by TimeForANinja** [comment]
ytdl-core provides all this information in way more detail
I can put it on the todo list
There is no real reason not to Support searching links - i just habe to find a decent way to differentiate between filter-links and literal search querys

**Comment by Tenclea** [comment]
> ytdl-core provides all this information in way more detail

Oh don't worry then, I'm sure I can figure it out then :)

Thanks anyways !

**Comment by MrZBou** [comment]
To be honest, link searches in the past ytsr were really faster than those of ytdl.getBasicInfo

**Comment by TimeForANinja** [comment]
added with v3.1.0
thanks for the feedback 👍🏿
