### ISSUE TITLE
"Unable to find JSON!" in some searches

### ISSUE THREAD

**Issue by dperales555** [TimeForANinja/node-ytsr#98]
In some searches for specific strings, 100% of the time I get this error: `Unable to find JSON!`.

The string that can be used to check for this error is "_candy plan b_".

I use the latest version available today: **ytsr@3.2.1**.

Full trace:
`Error: Unable to find JSON!
    at module.exports (/home/xxx/bot/node_modules/ytsr/lib/main.js:11:23)
    at module.exports (/home/xxx/bbot/node_modules/ytsr/lib/main.js:19:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.run (/home/xxx/bot/commands/play.js:391:17)
`

**Comment by TimeForANinja** [comment]
🤔 was able to recreate yesterday, but not today where i wanted to take a deeper look
lemme check again tomorrow

**Comment by batuhansahan** [comment]
+1 still an issue

**Comment by TimeForANinja** [comment]
dumped the page 👍 
looks like `utils#cutAfterJSON` is failing...

**Comment by TimeForANinja** [comment]
found the Problem...
the full code to recreate the error is
```js
require('./lib/utils.js').cutAfterJSON('{"text": "\\"};');
```
the `cutAfterJSON` is based on a ytdl-core method thou https://github.com/fent/node-ytdl-core/blob/master/lib/utils.js#L58

**Comment by TimeForANinja** [comment]
first fixed with https://github.com/fent/node-ytdl-core/pull/862
copied changes in https://github.com/TimeForANinja/node-ytsr/commits/master
released under v3.2.2

**Comment by batuhansahan** [comment]
after update i get 
` TypeError: filters.get(...).find is not a function`

**Comment by batuhansahan** [comment]
@TimeForANinja after update i get 
` TypeError: filters.get(...).find is not a function`

**Comment by TimeForANinja** [comment]
check the porting to v2 information here https://github.com/TimeForANinja/node-ytsr/releases/tag/2.0.0
been a while since that changed
filters is no longer a Map of Array but a Map of Maps

**Comment by dperales555** [comment]
> first fixed with https://github.com/fent/node-ytdl-core/pull/862
> copied changes in https://github.com/TimeForANinja/node-ytsr/commit/74e7fe453d741c625c0b834b8e8296c84df143f2
> released under [v3.2.2](https://github.com/TimeForANinja/node-ytsr/releases/tag/3.2.2)

    Thanks a lot for your work. It works pefectly.
