### ISSUE TITLE
failed at func parseItem: unknown message in messageRenderer

### ISSUE THREAD

**Issue by ChinHongTan** [TimeForANinja/node-ytsr#99]
os: win32-x64, node.js: v14.15.4, ytpl: 3.2.1
[gzqzhnueb-1611222562746.txt](https://github.com/TimeForANinja/node-ytsr/files/5849201/gzqzhnueb-1611222562746.txt)

**Comment by TimeForANinja** [comment]
🤔 so the messages actually change with the locals
guess i'll have to just ignore all messages instead of saving "no more videos" in all possible languages
